//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.05.07 at 10:47:23 PM TRT
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.packageConfig;

import javax.xml.namespace.QName;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.microsoft.schemas.windows_icd_package_config_v1 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class PackageConfigObjectFactory {

    private final static QName _PackageConfig_QNAME = new QName("urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0", "PackageConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.schemas.windows_icd_package_config_v1
     *
     */
    public PackageConfigObjectFactory() {
    }

    /**
     * Create an instance of {@link PackageConfigType }
     *
     */
    public PackageConfigType createPackageConfigType() {
        return new PackageConfigType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageConfigType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PackageConfigType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0", name = "PackageConfig")
    public JAXBElement<PackageConfigType> createPackageConfig(PackageConfigType value) {
        return new JAXBElement<PackageConfigType>(_PackageConfig_QNAME, PackageConfigType.class, null, value);
    }

}
