//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:47:23 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.packageConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for PackageConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageConfigType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OwnerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageConfig", propOrder = {
    "id",
    "name",
    "version",
    "ownerType",
    "rank",
    "notes"
})
public class PackageConfigType {

    @XmlElement(name = "ID", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String id;
    @XmlElement(name = "Name", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String name;
    @XmlElement(name = "Version", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String version;
    @XmlElement(name = "OwnerType", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String ownerType;
    @XmlElement(name = "Rank", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String rank;
    @XmlElement(name = "Notes", required = true, namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0")
    protected String notes;

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the ownerType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * Sets the value of the ownerType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOwnerType(String value) {
        this.ownerType = value;
    }

    /**
     * Gets the value of the rank property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNotes(String value) {
        this.notes = value;
    }
}
