//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:47:23 PM TRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.aekarakus.winconductor.sentinel.entities.xmblocks.packageConfig;
