spring:
  datasource:
    url: jdbc:h2:mem:kioskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

management:
  server:
    port: 8080

