//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.19 at 03:07:23 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import javax.xml.bind.annotation.*;
import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for CommandConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandConfigType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommandFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommandLine"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="cmd /c "chrome.exe""/&gt;
 *               &lt;enumeration value="dism /online /enable-feature /FeatureName:Client-EmbeddedShellLauncher /all"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ContinueInstall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RestartRequired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnCodeRestart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnCodeSuccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandConfigType", propOrder = {
    "commandFile",
    "commandLine",
    "continueInstall",
    "restartRequired",
    "returnCodeRestart",
    "returnCodeSuccess"
})
@Getter
@Setter
public class CommandConfigType {

    @XmlElement(name = "CommandFile")
    protected String commandFile;
    @XmlElement(name = "CommandLine", required = true)
    protected String commandLine;
    @XmlElement(name = "ContinueInstall")
    protected String continueInstall;
    @XmlElement(name = "RestartRequired")
    protected String restartRequired;
    @XmlElement(name = "ReturnCodeRestart")
    protected String returnCodeRestart;
    @XmlElement(name = "ReturnCodeSuccess")
    protected String returnCodeSuccess;
    @XmlAttribute(name = "Name")
    protected String name;

}
