//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for CommonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Accounts" type="{urn:schemas-microsoft-com:windows-provisioning}AccountsType"/&gt;
 *         &lt;element name="DevDetail" type="{urn:schemas-microsoft-com:windows-provisioning}DevDetailType"/&gt;
 *         &lt;element name="OOBE" type="{urn:schemas-microsoft-com:windows-provisioning}OOBEType"/&gt;
 *         &lt;element name="Policies" type="{urn:schemas-microsoft-com:windows-provisioning}PoliciesType"/&gt;
 *         &lt;element name="ProvisioningCommands" type="{urn:schemas-microsoft-com:windows-provisioning}ProvisioningCommandsType"/&gt;
 *         &lt;element name="SMISettings" type="{urn:schemas-microsoft-com:windows-provisioning}SMISettingsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonType", propOrder = {
    "accounts",
    "devDetail",
    "oobe",
    "policies",
    "provisioningCommands",
    "smiSettings"
})
@Getter
@Setter
public class CommonType {

    @XmlElement(name = "Accounts", required = true)
    protected AccountsType accounts;
    @XmlElement(name = "DevDetail", required = true)
    protected DevDetailType devDetail;
    @XmlElement(name = "OOBE", required = true)
    protected OOBEType oobe;
    @XmlElement(name = "Policies", required = true)
    protected PoliciesType policies;
    @XmlElement(name = "ProvisioningCommands", required = true)
    protected ProvisioningCommandsType provisioningCommands;
    @XmlElement(name = "SMISettings", required = true)
    protected SMISettingsType smiSettings;
}
