//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for CommandConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandConfigType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommandFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommandLine" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="cmd /c "chrome.exe""/&gt;
 *               &lt;enumeration value="dism /online /enable-feature /FeatureName:Client-EmbeddedShellLauncher /all"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ContinueInstall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RestartRequired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnCodeRestart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnCodeSuccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandConfigType", propOrder = {
    "content"
})
@Getter
@Setter
public class CommandConfigType {

    @XmlElementRefs({
        @XmlElementRef(name = "CommandFile", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommandLine", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ContinueInstall", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RestartRequired", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ReturnCodeRestart", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ReturnCodeSuccess", namespace = "urn:schemas-microsoft-com:windows-provisioning", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<JAXBElement<String>> content = new ArrayList<>();
    @XmlAttribute(name = "Name")
    protected String name;

}
