//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocalUserSpecificSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalUserSpecificSettingsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LocalUserShellSetting" type="{urn:schemas-microsoft-com:windows-provisioning}LocalUserShellSettingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalUserSpecificSettingsType", propOrder = {
    "localUserShellSetting"
})
public class LocalUserSpecificSettingsType {

    @XmlElement(name = "LocalUserShellSetting")
    protected List<LocalUserShellSettingType> localUserShellSetting;

    /**
     * Gets the value of the localUserShellSetting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the localUserShellSetting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalUserShellSetting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalUserShellSettingType }
     * 
     * 
     */
    public List<LocalUserShellSettingType> getLocalUserShellSetting() {
        if (localUserShellSetting == null) {
            localUserShellSetting = new ArrayList<LocalUserShellSettingType>();
        }
        return this.localUserShellSetting;
    }

}
