//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.05.07 at 10:38:46 PM TRT
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import javax.xml.namespace.QName;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.microsoft.schemas.windows_provisioning package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Settings_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "Settings");
    private final static QName _CommandConfigTypeCommandFile_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "CommandFile");
    private final static QName _CommandConfigTypeCommandLine_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "CommandLine");
    private final static QName _CommandConfigTypeContinueInstall_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "ContinueInstall");
    private final static QName _CommandConfigTypeRestartRequired_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "RestartRequired");
    private final static QName _CommandConfigTypeReturnCodeRestart_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "ReturnCodeRestart");
    private final static QName _CommandConfigTypeReturnCodeSuccess_QNAME = new QName("urn:schemas-microsoft-com:windows-provisioning", "ReturnCodeSuccess");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.schemas.windows_provisioning
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SettingsType }
     *
     */
    public SettingsType createSettingsType() {
        return new SettingsType();
    }

    /**
     * Create an instance of {@link UserType }
     *
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UsersType }
     *
     */
    public UsersType createUsersType() {
        return new UsersType();
    }

    /**
     * Create an instance of {@link AccountsType }
     *
     */
    public AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link DevDetailType }
     *
     */
    public DevDetailType createDevDetailType() {
        return new DevDetailType();
    }

    /**
     * Create an instance of {@link DesktopType }
     *
     */
    public DesktopType createDesktopType() {
        return new DesktopType();
    }

    /**
     * Create an instance of {@link OOBEType }
     *
     */
    public OOBEType createOOBEType() {
        return new OOBEType();
    }

    /**
     * Create an instance of {@link ApplicationManagementType }
     *
     */
    public ApplicationManagementType createApplicationManagementType() {
        return new ApplicationManagementType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     *
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link CommandConfigType }
     *
     */
    public CommandConfigType createCommandConfigType() {
        return new CommandConfigType();
    }

    /**
     * Create an instance of {@link CommandType }
     *
     */
    public CommandType createCommandType() {
        return new CommandType();
    }

    /**
     * Create an instance of {@link PrimaryContextType }
     *
     */
    public PrimaryContextType createPrimaryContextType() {
        return new PrimaryContextType();
    }

    /**
     * Create an instance of {@link ProvisioningCommandsType }
     *
     */
    public ProvisioningCommandsType createProvisioningCommandsType() {
        return new ProvisioningCommandsType();
    }

    /**
     * Create an instance of {@link AutoLogonType }
     *
     */
    public AutoLogonType createAutoLogonType() {
        return new AutoLogonType();
    }

    /**
     * Create an instance of {@link LocalUserShellSettingType }
     *
     */
    public LocalUserShellSettingType createLocalUserShellSettingType() {
        return new LocalUserShellSettingType();
    }

    /**
     * Create an instance of {@link LocalUserSpecificSettingsType }
     *
     */
    public LocalUserSpecificSettingsType createLocalUserSpecificSettingsType() {
        return new LocalUserSpecificSettingsType();
    }

    /**
     * Create an instance of {@link UserSpecificSettingsType }
     *
     */
    public UserSpecificSettingsType createUserSpecificSettingsType() {
        return new UserSpecificSettingsType();
    }

    /**
     * Create an instance of {@link ShellLauncherType }
     *
     */
    public ShellLauncherType createShellLauncherType() {
        return new ShellLauncherType();
    }

    /**
     * Create an instance of {@link SMISettingsType }
     *
     */
    public SMISettingsType createSMISettingsType() {
        return new SMISettingsType();
    }

    /**
     * Create an instance of {@link CommonType }
     *
     */
    public CommonType createCommonType() {
        return new CommonType();
    }

    /**
     * Create an instance of {@link CustomizationsType }
     *
     */
    public CustomizationsType createCustomizationsType() {
        return new CustomizationsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SettingsType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SettingsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "Settings")
    public JAXBElement<SettingsType> createSettings(SettingsType value) {
        return new JAXBElement<SettingsType>(_Settings_QNAME, SettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "CommandFile", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeCommandFile(String value) {
        return new JAXBElement<String>(_CommandConfigTypeCommandFile_QNAME, String.class, CommandConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "CommandLine", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeCommandLine(String value) {
        return new JAXBElement<String>(_CommandConfigTypeCommandLine_QNAME, String.class, CommandConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "ContinueInstall", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeContinueInstall(String value) {
        return new JAXBElement<String>(_CommandConfigTypeContinueInstall_QNAME, String.class, CommandConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "RestartRequired", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeRestartRequired(String value) {
        return new JAXBElement<String>(_CommandConfigTypeRestartRequired_QNAME, String.class, CommandConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "ReturnCodeRestart", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeReturnCodeRestart(String value) {
        return new JAXBElement<String>(_CommandConfigTypeReturnCodeRestart_QNAME, String.class, CommandConfigType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:schemas-microsoft-com:windows-provisioning", name = "ReturnCodeSuccess", scope = CommandConfigType.class)
    public JAXBElement<String> createCommandConfigTypeReturnCodeSuccess(String value) {
        return new JAXBElement<String>(_CommandConfigTypeReturnCodeSuccess_QNAME, String.class, CommandConfigType.class, value);
    }

}
