//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.12 at 07:41:45 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:schemas-microsoft-com:windows-provisioning",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;
