//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimaryContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrimaryContextType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Command" type="{urn:schemas-microsoft-com:windows-provisioning}CommandType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimaryContextType", propOrder = {
    "command"
})
public class PrimaryContextType {

    @XmlElement(name = "Command", required = true)
    protected CommandType command;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link CommandType }
     *     
     */
    public CommandType getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandType }
     *     
     */
    public void setCommand(CommandType value) {
        this.command = value;
    }

}
