//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShellLauncherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShellLauncherType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Enable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UserSpecificSettings" type="{urn:schemas-microsoft-com:windows-provisioning}UserSpecificSettingsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShellLauncherType", propOrder = {
    "enable",
    "userSpecificSettings"
})
public class ShellLauncherType {

    @XmlElement(name = "Enable", required = true)
    protected String enable;
    @XmlElement(name = "UserSpecificSettings", required = true)
    protected UserSpecificSettingsType userSpecificSettings;

    /**
     * Gets the value of the enable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnable(String value) {
        this.enable = value;
    }

    /**
     * Gets the value of the userSpecificSettings property.
     * 
     * @return
     *     possible object is
     *     {@link UserSpecificSettingsType }
     *     
     */
    public UserSpecificSettingsType getUserSpecificSettings() {
        return userSpecificSettings;
    }

    /**
     * Sets the value of the userSpecificSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserSpecificSettingsType }
     *     
     */
    public void setUserSpecificSettings(UserSpecificSettingsType value) {
        this.userSpecificSettings = value;
    }

}
