//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SMISettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMISettingsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AutoLogon" type="{urn:schemas-microsoft-com:windows-provisioning}AutoLogonType"/&gt;
 *         &lt;element name="HideAutologonUI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ShellLauncher" type="{urn:schemas-microsoft-com:windows-provisioning}ShellLauncherType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMISettingsType", propOrder = {
    "autoLogon",
    "hideAutologonUI",
    "shellLauncher"
})
public class SMISettingsType {

    @XmlElement(name = "AutoLogon", required = true)
    protected AutoLogonType autoLogon;
    @XmlElement(name = "HideAutologonUI", required = true)
    protected String hideAutologonUI;
    @XmlElement(name = "ShellLauncher", required = true)
    protected ShellLauncherType shellLauncher;

    /**
     * Gets the value of the autoLogon property.
     * 
     * @return
     *     possible object is
     *     {@link AutoLogonType }
     *     
     */
    public AutoLogonType getAutoLogon() {
        return autoLogon;
    }

    /**
     * Sets the value of the autoLogon property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoLogonType }
     *     
     */
    public void setAutoLogon(AutoLogonType value) {
        this.autoLogon = value;
    }

    /**
     * Gets the value of the hideAutologonUI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideAutologonUI() {
        return hideAutologonUI;
    }

    /**
     * Sets the value of the hideAutologonUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideAutologonUI(String value) {
        this.hideAutologonUI = value;
    }

    /**
     * Gets the value of the shellLauncher property.
     * 
     * @return
     *     possible object is
     *     {@link ShellLauncherType }
     *     
     */
    public ShellLauncherType getShellLauncher() {
        return shellLauncher;
    }

    /**
     * Sets the value of the shellLauncher property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShellLauncherType }
     *     
     */
    public void setShellLauncher(ShellLauncherType value) {
        this.shellLauncher = value;
    }

}
