//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for SMISettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMISettingsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AutoLogon" type="{urn:schemas-microsoft-com:windows-provisioning}AutoLogonType"/&gt;
 *         &lt;element name="HideAutologonUI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ShellLauncher" type="{urn:schemas-microsoft-com:windows-provisioning}ShellLauncherType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMISettingsType", propOrder = {
    "autoLogon",
    "hideAutologonUI",
    "shellLauncher"
})
@Getter
@Setter
public class SMISettingsType {

    @XmlElement(name = "AutoLogon", required = true, namespace = "urn:schemas-microsoft-com:windows-provisioning")
    protected AutoLogonType autoLogon;
    @XmlElement(name = "HideAutologonUI", required = true, namespace = "urn:schemas-microsoft-com:windows-provisioning")
    protected String hideAutologonUI;
    @XmlElement(name = "ShellLauncher", required = true, namespace = "urn:schemas-microsoft-com:windows-provisioning")
    protected ShellLauncherType shellLauncher;


}
