//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 10:38:46 PM TRT 
//


package io.aekarakus.winconductor.sentinel.entities.xmblocks.windowsCustomizations;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserSpecificSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserSpecificSettingsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LocalUserSpecificSettings" type="{urn:schemas-microsoft-com:windows-provisioning}LocalUserSpecificSettingsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserSpecificSettingsType", propOrder = {
    "localUserSpecificSettings"
})
public class UserSpecificSettingsType {

    @XmlElement(name = "LocalUserSpecificSettings", required = true)
    protected LocalUserSpecificSettingsType localUserSpecificSettings;

    /**
     * Gets the value of the localUserSpecificSettings property.
     * 
     * @return
     *     possible object is
     *     {@link LocalUserSpecificSettingsType }
     *     
     */
    public LocalUserSpecificSettingsType getLocalUserSpecificSettings() {
        return localUserSpecificSettings;
    }

    /**
     * Sets the value of the localUserSpecificSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalUserSpecificSettingsType }
     *     
     */
    public void setLocalUserSpecificSettings(LocalUserSpecificSettingsType value) {
        this.localUserSpecificSettings = value;
    }

}
