////
//// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2024.05.12 at 07:41:45 PM TRT
////
//
//@jakarta.xml.bind.annotation.XmlSchema(
//        namespace = "", elementFormDefault = XmlNsForm.QUALIFIED)
//package io.aekarakus.winconductor.sentinel.entities;
//
//import jakarta.xml.bind.annotation.XmlNsForm;